----- DO NOT CHANGE ANYTHING IN THIS FILE ------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DATABASE registrar;

\connect registrar
CREATE EXTENSION IF NOT EXISTS pgcrypto;

----- DO NOT CHANGE ANYTHING IN THIS FILE ------