----- DO NOT CHANGE ANYTHING IN THIS FILE ------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DATABASE vehicle;

\connect vehicle
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS dblink; 

----- DO NOT CHANGE ANYTHING IN THIS FILE ------