services:
  postgres:
    container_name: cse187-assignment-1
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/databases.test.sql:/docker-entrypoint-initdb.d/1.databases.test.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./sql/test.sql:/docker-entrypoint-initdb.d/3.test.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/4.data.sql
