name: Integration - Lint, Build, and Test

on:
  push:
    tags:
      # Version the tag as you can only use a tag once
      - "integration-v*.*.*"
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  deploy-docker:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npm run installs
      # Verify the build
      - run: npm run build

      # Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build and push Docker image
      - name: Build Tagged Docker Image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          REPO_OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$REPO_OWNER/virtual-park:$VERSION
          docker build . -t $IMAGE --platform linux/amd64
          docker push $IMAGE

      # I had ChatGPT generate the lowercase conversion, which is why it failed the first time
      - name: Tag and Push as Latest
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          REPO_OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$REPO_OWNER/virtual-park:$VERSION
          LATEST=ghcr.io/$REPO_OWNER/virtual-park:latest
          docker tag $IMAGE $LATEST
          docker push $LATEST

  deploy:
    name: Deploy and Spin Up on EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH into EC2 and Deploy
        run: echo "This would ssh into EC2, pull the latest image, and run npm run containerised"
