name: Integration - Lint, Build, and Test

on:
  push:
    tags:
      - 'integration-v*.*.*'

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      # Have the runner execute in a branch
      - uses: actions/checkout@v4
      # Setup node env w/ lts version
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm run lint
